#!/bin/bash

echo "=============================================================="
echo "Verificando se o Atom está instalado"
echo "=============================================================="
    if which -a "atom"
    then
        echo "Atom já está instalado."
    else
        echo "=============================================================="
        echo "Baixando Atom"
        echo "=============================================================="
        wget https://atom.io/download/deb -O atom-amd64.deb
        echo "=============================================================="
        echo "Instalando Atom"
        echo "=============================================================="
        sudo apt-get install ./atom-amd64.deb
    fi
echo "=============================================================="
echo "Copiando configuração do Atom"
echo "=============================================================="
    cp config.cson ~/.atom/
    echo "Copiado com sucesso!"
echo "=============================================================="
echo "Instalando packages listados do Atom"
echo "=============================================================="
apm install --packages-file package.list
echo "=============================================================="
echo "Atualizando os packages do Atom para última versão"
echo "=============================================================="
apm upgrade --no-confirm
echo "=============================================================="
echo "Sobrescrevendo a lista com as versões novas"
echo "=============================================================="
apm list --installed --bare > ./package.list
echo "PROCESSO CONCLUIDO"
echo "=============================================================="
rm atom-amd64.deb
